header:
	@echo "For Work With openemr"
up:
	docker compose up 
down:
	docker compose down
stop:
	docker compose stop
start:
	docker compose start
exec:
	docker exec -it mysql bash
hello:
	@echo "All Right"